# -*- mode: yaml; coding: utf-8 -*-
# Copyright (C) 2025 Benjamin Thomas Schwertfeger
#
# https://github.com/btschwertfeger
#
on:
  push:
    tags:
      - "*"

name: Deploy Extension
jobs:
  deploy:
    environment:
      name: Visual Studio Marketplace
      url: https://marketplace.visualstudio.com/items?itemName=btschwertfeger.uckingnice&ssr=false#overview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
